- name: "Create user config file directories, if not exist"
  ansible.builtin.file:
    path: "{{ yazi_config_file_path | dirname }}"
    state: directory
  become: true
  become_user: "{{ yazi_user_name }}"

- name: "Create user image cache directory, if not exist"
  ansible.builtin.file:
    path: "{{ yazi_image_cache_dir }}"
    state: directory
  become: true
  become_user: "{{ yazi_user_name }}"
  changed_when: false

- name: "Configure all Yazi behavior in '{{ yazi_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ yazi_config_file_path }}"
    src: "yazi_toml.j2"
  become: true
  become_user: "{{ yazi_user_name }}"

- name: "Configure all Yazi keymaps in '{{ yazi_keymap_file_path }}'"
  ansible.builtin.template:
    dest: "{{ yazi_keymap_file_path }}"
    src: "keymap_toml.j2"
  become: true
  become_user: "{{ yazi_user_name }}"

